server:
  port: 8182

spring:
  datasource:
    url: "jdbc:postgresql://localhost:6543/custom-provider"
    username: "postgres"
    password: "12345"
    driver-class-name: org.postgresql.Driver
  jpa:
    properties.hibernate:
      dialect: org.hibernate.dialect.PostgreSQLDialect
      format_sql: true
    show-sql: true
    hibernate:
      ddl-auto: update
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:9090/realms/Assignment


idp:
  url: http://localhost:9090
  client-id: assignment1
  client-secret: dOt5xW5P3XgrN42gCkTJe3pwdYnCIfOS
keycloak:
  realm: Assignment
  admin-username: admin
  admin-password: 12345678

