server:
  port: 8182
  servlet:
    context-path: /bookstore


spring:
  datasource:
    url: "jdbc:postgresql://localhost:6543/book-store-db"
    username: "postgres"
    password: "12345"
    driver-class-name: org.postgresql.Driver
  jpa:
    properties.hibernate:
      dialect: org.hibernate.dialect.PostgreSQLDialect
      format_sql: true
    show-sql: true
    hibernate:
      ddl-auto: update
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:9090/realms/Assignment


idp:
  url: http://localhost:9090
  client-id: assignment1
  client-secret: KV0G7UPVZIgQ0EYpbh5Yj3zQfGUbuDCh
keycloak:
  realm: Assignment
  admin-username: admin
  admin-password: admin123


storage:
  location: uploads/images

